name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Docker (if Docker is not already available on the runner)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Cache Docker layers to speed up the build process
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build . --file ./docker/Dockerfile --tag swimpyblaq92/chima:1734463639
      working-directory: ./path/to/your/directory  # Replace with the correct path if needed

    # Optionally, push the Docker image to a registry (like Docker Hub or GitHub Container Registry)
    - name: Push Docker image
      run: |
        docker push swimpyblaq92/chima:1734463639
      if: success()  # Only push if the build succeeds
