name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Debug repository structure
      run: |
        ls -R

    - name: Verify Dockerfile Path
      run: |
        if [ ! -f ./app/docker/Dockerfile ]; then
          echo "ERROR: Dockerfile not found at ./app/docker/Dockerfile. Please check the path.";
          exit 1;
        fi

    - name: Build Docker image
      run: |
        docker build . --file ./app/docker/Dockerfile --tag swimpyblaq/chima:latest
